
 exports.array = [
    {
    "deck_id": 1,
    "name": 'as',
    "point_value": 1,
    "category": 'ace',
    "suit": 'spade',
    "costume_url": '',
},
{
    "deck_id": 2,
    "name": '2s',
    "point_value": 2,
    "category": 'pip',
    "suit": 'spade',
    "costume_url": '',
},
{
    "deck_id": 3,
    "name": '3s',
    "point_value": 3,
    "category": 'pip',
    "suit": 'spade',
    "costume_url": '',
},
{
"deck_id": 4,
    "name": '4s',
    "point_value": 4,
    "category": 'pip',
    "suit": 'spade',
    "costume_url": '',
},
{
    "deck_id": 5,
    "name": '5s',
    "point_value": 5,
    "category": 'pip',
    "suit": 'spade',
    "costume_url": '',
},
{
    "deck_id": 6,
    "name": '6s',
    "point_value": 6,
    "category": 'pip',
    "suit": 'spade',
    "costume_url": '',
},
{
    "deck_id": 7,
    "name": '7s',
    "point_value": 7,
    "category": 'pip',
    "suit": 'spade',
    "costume_url": '',
},
{
    "deck_id": 8,
    "name": '8s',
    "point_value": 8,
    "category": 'pip',
    "suit": 'spade',
    "costume_url": '',
},
{
    "deck_id": 9,
    "name": '9s',
    "point_value": 9,
    "category": 'pip',
    "suit": 'spade',
    "costume_url": '',
},
{
    "deck_id": 10,
    "name": '10s',
    "point_value": 10,
    "category": 'pip',
    "suit": 'spade',
    "costume_url": '',
},
{
    "deck_id": 11,
    "name": 'js',
    "point_value": 10,
    "category": 'face',
    "suit": 'spade',
    "costume_url": '',
},
{
    "deck_id": 12,
    "name": 'qs',
    "point_value": 10,
    "category": 'face',
    "suit": 'spade',
    "costume_url": '',
},
{
    "deck_id": 13,
    "name": 'ks',
    "point_value": 10,
    "category": 'face',
    "suit": 'spade',
    "costume_url": '',
},
{
    "deck_id": 14,
    "name": 'ah',
    "point_value": 1,
    "category": 'ace',
    "suit": 'heart',
    "costume_url": '',
},
{
    "deck_id": 15,
    "name": '2h',
    "point_value": 2,
    "category": 'pip',
    "suit": 'heart',
    "costume_url": '',
},
{
    "deck_id": 16,
    "name": '3h',
    "point_value": 3,
    "category": 'pip',
    "suit": 'heart',
    "costume_url": '',
},
{
    "deck_id": 17,
    "name": '4h',
    "point_value": 4,
    "category": 'pip',
    "suit": 'heart',
    "costume_url": '',
},
{
    "deck_id": 18,
    "name": '5h',
    "point_value": 5,
    "category": 'pip',
    "suit": 'heart',
    "costume_url": '',
},
{
    "deck_id": 19,
    "name": '6h',
    "point_value": 6,
    "category": 'pip',
    "suit": 'heart',
    "costume_url": '',
},
{
    "deck_id": 20,
    "name": '7h',
    "point_value": 7,
    "category": 'pip',
    "suit": 'heart',
    "costume_url": '',
},
{
    "deck_id": 21,
    "name": '8h',
    "point_value": 8,
    "category": 'pip',
    "suit": 'heart',
    "costume_url": '',
},
{
    "deck_id": 22,
    "name": '9',
    "point_value": 9,
    "category": 'pip',
    "suit": 'heart',
    "costume_url": '',
},
{
    "deck_id": 23,
    "name": '10h',
    "point_value": 10,
    "category": 'face',
    "suit": 'heart',
    "costume_url": '',
},
{
    "deck_id": 24,
    "name": 'jh',
    "point_value": 10,
    "category": 'face',
    "suit": 'heart',
    "costume_url": '',
},
{
    "deck_id": 25,
    "name": 'qh',
    "point_value": 10,
    "category": 'face',
    "suit": 'heart',
    "costume_url": '',
},
{
    "deck_id": 26,
    "name": 'kh',
    "point_value": 10,
    "category": 'face',
    "suit": 'heart',
    "costume_url": '',
},
{
    "deck_id": 27,
    "name": 'ad',
    "point_value": 1,
    "category": 'ace',
    "suit": 'diamond',
    "costume_url": '',
},
{
    "deck_id": 28,
    "name": '2d',
    "point_value": 2,
    "category": 'pip',
    "suit": 'diamond',
    "costume_url": '',
},
{
    "deck_id": 29,
    "name": '3d',
    "point_value": 3,
    "category": 'pip',
    "suit": 'diamond',
    "costume_url": '',
},
{
    "deck_id": 30,
    "name": '4d',
    "point_value": 4,
    "category": 'pip',
    "suit": 'diamond',
    "costume_url": '',
},
{
    "deck_id": 31,
    "name": '5d',
    "point_value": 5,
    "category": 'pip',
    "suit": 'diamond',
    "costume_url": '',
},
{
    "deck_id": 32,
    "name": '6d',
    "point_value": 6,
    "category": 'pip',
    "suit": 'diamond',
    "costume_url": '',
},
{
    "deck_id": 33,
    "name": '7d',
    "point_value": 7,
    "category": 'pip',
    "suit": 'diamond',
    "costume_url": '',
},
{
    "deck_id": 34,
    "name": '8d',
    "point_value": 8,
    "category": 'pip',
    "suit": 'diamond',
    "costume_url": '',
},
{
    "deck_id": 35,
"name": '9d',
    "point_value": 9,
    "category": 'pip',
    "suit": 'diamond',
    "costume_url": '',
},
{
    "deck_id": 36,
    "name": '10d',
    "point_value": 10,
    "category": '',
    "suit": 'diamond',
    "costume_url": '',
},
{
    "deck_id": 37,
    "name": 'jd',
    "point_value": 10,
    "category": '',
    "suit": 'diamond',
    "costume_url": '',
},
{
    "deck_id": 38,
    "name": 'qd',
    "point_value": 10,
    "category": '',
    "suit": 'diamond',
    "costume_url": '',
},
{
    "deck_id": 39,
    "name": 'kd',
    "point_value": 10,
    "category": '',
    "suit": 'diamond',
    "costume_url": '',
},
{
    "deck_id": 40,
    "name": 'ac',
    "point_value": 1,
    "category": 'ace',
    "suit": 'club',
    "costume_url": '',
},
{
    "deck_id": 41,
    "name": '2c',
    "point_value": 2,
    "category": 'pip',
    "suit": 'club',
    "costume_url": '',
},
{
    "deck_id": 42,
    "name": '3c',
    "point_value": 3,
    "category": 'pip',
    "suit": 'club',
    "costume_url": '',
},
{
    "deck_id": 43,
    "name": '4c',
    "point_value": 4,
    "category": 'pip',
    "suit": 'club',
    "costume_url": '',
},
{
    "deck_id": 44,
    "name": '5c',
    "point_value": 5,
    "category": 'pip',
    "suit": 'club',
    "costume_url": '',
},
{
    "deck_id": 45,
    "name": '6c',
    "point_value": 6,
    "category": 'pip',
    "suit": 'club',
    "costume_url": '',
},
{
    "deck_id": 46,
    "name": '7c',
    "point_value": 7,
    "category": 'pip',
    "suit": 'club',
    "costume_url": '',
},
{
    "deck_id": 47,
    "name": '8c',
    "point_value": 8,
    "category": 'pip',
    "suit": 'club',
    "costume_url": '',
},
{
    "deck_id": 48,
    "name": '9c',
    "point_value": 9,
    "category": 'pip',
    "suit": 'club',
    "costume_url": 'face',
},
{
    "deck_id": 49,
    "name": '10c',
    "point_value": 10,
    "category": 'face',
    "suit": 'club',
    "costume_url": '',
},
{
    "deck_id": 50,
    "name": 'jc',
    "point_value": 10,
    "category": 'face',
    "suit": 'club',
    "costume_url": '',
},
{
    "deck_id": 51,
    "name": 'qc',
    "point_value": 10,
    "category": 'face',
    "suit": 'club',
    "costume_url": '',
},
{
    "deck_id": 52,
    "name": 'kc',
    "point_value": 10,
    "category": 'face',
    "suit": 'club',
    "costume_url": '',
},

];
